version: '3'

services:
  users:
    build: ./users_backend
    ports:
      - 8000:8000
    environment:
      - TZ=Europe/Lisbon
    networks:
      - users
    depends_on:
      - users-mysql

  users-mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - users-mysql-data:/var/lib/mysql
    networks:
      - users
    environment:
      - MYSQL_DATABASE=user
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Europe/Lisbon

volumes:
  users-mysql-data:

networks:
  users:
    driver: bridge