"""
Django settings for users_backend project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-)#f(t5%m3v8ywv=%htz=d$zf-q(py5g3=&1p%4es*hpbg^gv!#"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "users",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "users_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "users_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        'NAME': 'user',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': 'users-mysql',
        'PORT': '3306',
  }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "pt-pt"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated'
    ),

    'DEFAULT_AUTHENTICATION_CLASSES': (
    'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

AUTH_USER_MODEL='users.User'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,

    'ALGORITHM': "RS256",
    "SIGNING_KEY": '-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCfrbrqvkiVaLRGjGCo0Rgy0FiMYqtOn+cT08bAiK573kt1tOUW7vQxOrKjMKKmkCTYJcwiZ39IAzkY0MziLTqcNRRpEvjFFpymui7lsafz8djsnW+k5Z2+dJhU1ZRhE2ZiBUKTGIbq3jDkmyGB/sm9mtSUHVHRv8STSy08Oy03ah1GT2LdnqaevCzOO6vB/o+zayX2Zf8Qdo4lCutkVLn4aZKKVRwthj10bIIfqWljM6SqNAhkCt1nju2B43q8UR8wjIeOa9R91BaarRaAMll9scxbCTRyrfPvxPzkzUducCCU98ZRG37m8X7c3NuLUF0jDm/YR6owr+UaollqHrlNAgMBAAECggEAI8gsoLnvTfvemgiPCIWCpLBnh139AWt3vsuwOCjo4L0Zr9DPnWoCsp1ytnsJl8WpW/5sVjFXJm4Cd3siznRQM/z5C+rCcHf2tq32IGbFOjcx4yQMhqklxi4ejLQnwfE0+jYviwLuCOetkSzqP1U3JBP0GxTO5u/QPymTg3HHWilEsuDdEo/OvGmBstodfPisdYeLaIY8qrvaiVtnUgEX77loF/kfGoOi9VS3xZ81z0OvRToDDBmE5NJOJWYVYTr634rKg4E50H347iXMKshJbGcD6YrTTWjLFurfL71BpXoUjw1mLn+6SBPKirC916rS5u95YDgIXXy2iFASv4YSQQKBgQDM2ByXStkJcSF3XePVkUI8Ci/2JyIegtwxBCqXFw8qPKbzgAX5vvuPaUmDzJWRsYuNAWLzMM2L0e1wQLUdlrBht899FXT3nVf2QJ6r0oCSwmaMRvVTfuy5z+qDqyrLohRb1kVHvvKoEkljFcRfdxNtnxDv35JiqTWXicE6wpJl2QKBgQDHjiQDm8BTt7pT4rKLbMRj3m6py2bKDKuHd02UHJh3jxytB/yqFzJYis+mvg4rdjlJvevjRjH4icGmrVt/f8cWd9Z9ciuoTuZvI++giCx9rmv7NsnZfMPnHs7lrHdVb6CWdjevWKMORDeqAss3+/YwOcuAL6C8HrH6pL2lO7PClQKBgQCdw0ux0bl6JiEqN6uDDk6+wvHRWK5UZWCEd7r9hortcqz6GH2BrW89Mk+mLGh9PwpFXO4CcnG738BIle1njmjluZUZtu7QzeOzCm2p04OmhAZKv1OuLLDRIqpxIeDh2EBpwoq1CQEGJJ9Uqq0FAUZ7ROjcdYneZoeZ4ERrpvLtcQKBgFd0CoJuUoYd4ZF7qwWBQDwIMfVFh6GKle2DMkNzmLnkxQtrkaY1DkJRaxlG90zCve58RhFPJP0n2e8i0BN7OxO0pxJI46saENCqLgzrQJw/wWDRrPocPHpgPQnYYF/X0Me/vT2iGatZ6A8gtFCvoj+WRIHD3awzw4n1gosUM/5VAoGAS8HLZlWrEy6+8QVAXVCkPe7SVmj4dfIAhMAdUBuNnJbAZOgA3P0bL0xAie4prztdcSxvn/JrYeF8y/+C0ekQNmX6Z4rBBLDasbH4ssw1rKhYcS+i0R6xQcpeiGdA3e1SOzuww1ciy8zuW2sYQluEVjo3fCtGoTmtnG1ZUv00p8k=\n-----END PRIVATE KEY-----',
    "VERIFYING_KEY": '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn6266r5IlWi0RoxgqNEYMtBYjGKrTp/nE9PGwIiue95LdbTlFu70MTqyozCippAk2CXMImd/SAM5GNDM4i06nDUUaRL4xRacprou5bGn8/HY7J1vpOWdvnSYVNWUYRNmYgVCkxiG6t4w5Jshgf7JvZrUlB1R0b/Ek0stPDstN2odRk9i3Z6mnrwszjurwf6Ps2sl9mX/EHaOJQrrZFS5+GmSilUcLYY9dGyCH6lpYzOkqjQIZArdZ47tgeN6vFEfMIyHjmvUfdQWmq0WgDJZfbHMWwk0cq3z78T85M1HbnAglPfGURt+5vF+3Nzbi1BdIw5v2EeqMK/lGqJZah65TQIDAQAB\n-----END PUBLIC KEY-----',
    }
